# GitHub Sponsors funding links
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom: https://donate.stripe.com/aFa28kbrLeb45mFgFE1ZS00