"""Backwards-compatibility tests for settings.json forward/backward compat.

Loads legacy settings.json fixtures (generated by cloud agent — see
fixtures/legacy_settings/CLOUD_AGENT_INSTRUCTIONS.md) and verifies that
load_persisted_settings() / _sanitize_settings_payload() correctly handle
every historical key-set.

Tests skip cleanly if no fixtures are present yet.
"""

import pytest
import json
from pathlib import Path
import sys
from unittest import mock

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from settings_utils import (
    _sanitize_settings_payload,
    _apply_monotonic_guard,
    load_persisted_settings,
    save_persisted_settings,
)


FIXTURE_DIR = Path(__file__).parent.parent / "fixtures" / "legacy_settings"


def _list_legacy_settings_fixtures():
    """Return list of settings JSON fixture paths."""
    if not FIXTURE_DIR.exists():
        return []
    return sorted([f for f in FIXTURE_DIR.glob("settings_v_*.json")])


_LEGACY_SETTINGS = _list_legacy_settings_fixtures()

_skip_no_settings_fixtures = pytest.mark.skipif(
    not _LEGACY_SETTINGS,
    reason="No legacy settings fixtures present yet — pending cloud agent work."
)

pytestmark = pytest.mark.compat


def _load_fixture_dict(path: Path) -> dict:
    with open(path, encoding='utf-8') as f:
        return json.load(f)


@_skip_no_settings_fixtures
@pytest.mark.parametrize(
    "fixture_path",
    _LEGACY_SETTINGS if _LEGACY_SETTINGS else [None],
    ids=[p.name for p in _LEGACY_SETTINGS] if _LEGACY_SETTINGS else ["no-fixtures"]
)
class TestLegacySettingsLoad:
    """Tests that run against every settings fixture."""

    def test_sanitize_does_not_crash(self, fixture_path):
        """_sanitize_settings_payload must succeed on every legacy fixture."""
        original = _load_fixture_dict(fixture_path)
        result = _sanitize_settings_payload(original)
        assert isinstance(result, dict)

    def test_no_known_keys_dropped(self, fixture_path):
        """Every key in the fixture should still be present after sanitization."""
        original = _load_fixture_dict(fixture_path)
        result = _sanitize_settings_payload(original)

        dropped = [k for k in original.keys() if k not in result]
        # We allow dropping ONLY if the value type was clearly invalid; for these
        # synthesized fixtures, values are always valid, so nothing should drop.
        assert not dropped, f"{fixture_path.name}: dropped keys {dropped}"

    def test_monotonic_counters_preserved(self, fixture_path):
        """Counters in the fixture are not zeroed or lowered after sanitization."""
        original = _load_fixture_dict(fixture_path)
        result = _sanitize_settings_payload(original)

        for key in ('kestrel_impact_total_files', 'kestrel_impact_total_seconds'):
            if key in original:
                assert key in result, f"{fixture_path.name}: counter {key} disappeared"
                # Values should be comparable (numeric)
                assert result[key] >= original[key], (
                    f"{fixture_path.name}: counter {key} regressed "
                    f"({original[key]} → {result[key]})"
                )


class TestForwardCompatibility:
    """Tests that unknown 'future' keys pass through sanitization untouched."""

    def test_with_future_keys_fixture(self):
        """Fixtures named *_with_future_keys.json should keep unknown keys after sanitize."""
        future_fixtures = [f for f in _LEGACY_SETTINGS if "_with_future_keys" in f.name]
        if not future_fixtures:
            pytest.skip("No _with_future_keys fixtures present")

        for fixture_path in future_fixtures:
            original = _load_fixture_dict(fixture_path)
            result = _sanitize_settings_payload(original)

            # Find keys we expect to be "future"/unknown
            # Heuristic: any key not in result is a problem
            for key, val in original.items():
                if key not in result:
                    pytest.fail(
                        f"{fixture_path.name}: forward-compat key '{key}' was dropped"
                    )


class TestDetectorNameMigration:
    """The 'fast' detector was switched from mdv6-e to mdv1000-cedar at v2.0.2.

    Stored settings carrying the legacy name should be silently rewritten on
    load — the user-facing 'Fast'/'Accurate' selector is unchanged.
    """

    def test_legacy_mdv6e_migrates_to_cedar(self):
        result = _sanitize_settings_payload({'detector_name': 'mdv6-e'})
        assert result['detector_name'] == 'mdv1000-cedar'

    def test_legacy_mdv6e_case_insensitive(self):
        for variant in ('MDv6-E', '  mdv6-e  ', 'MDV6-E'):
            result = _sanitize_settings_payload({'detector_name': variant})
            assert result['detector_name'] == 'mdv1000-cedar', f"failed for {variant!r}"

    def test_mdv5a_passes_through(self):
        result = _sanitize_settings_payload({'detector_name': 'mdv5a'})
        assert result['detector_name'] == 'mdv5a'

    def test_cedar_passes_through(self):
        result = _sanitize_settings_payload({'detector_name': 'mdv1000-cedar'})
        assert result['detector_name'] == 'mdv1000-cedar'

    def test_unknown_name_falls_back_to_default(self):
        # _coerce_enum default when the value isn't allowlisted
        result = _sanitize_settings_payload({'detector_name': 'made-up-name'})
        assert result['detector_name'] == 'mdv5a'

    def test_gambels_quail_fixture_migrates(self):
        """The Gambels-Quail fixture carries detector_name='mdv6-e' on purpose
        so this migration path is exercised whenever fixtures are regenerated."""
        fixture = FIXTURE_DIR / "settings_v_Gambels-Quail.json"
        if not fixture.exists():
            pytest.skip("Gambels-Quail fixture not present")
        original = _load_fixture_dict(fixture)
        assert original.get('detector_name') == 'mdv6-e', (
            "Fixture should still carry the legacy name to exercise the migration"
        )
        result = _sanitize_settings_payload(original)
        assert result['detector_name'] == 'mdv1000-cedar'


class TestMonotonicGuardScenarios:
    """Specific scenarios where the monotonic guard must hold across load/save."""

    def test_save_with_lower_counter_preserves_higher(self):
        """If saved settings have higher counter than incoming, higher wins."""
        existing = {'kestrel_impact_total_files': 1000}
        incoming = {'kestrel_impact_total_files': 500}

        result = _apply_monotonic_guard(incoming, existing)
        assert result['kestrel_impact_total_files'] == 1000

    def test_omitted_counter_resurrected_from_existing(self):
        """If incoming omits a counter, existing value is restored."""
        existing = {'kestrel_impact_total_files': 1000}
        incoming = {'other_key': 'value'}

        result = _apply_monotonic_guard(incoming, existing)
        assert result.get('kestrel_impact_total_files') == 1000

    def test_higher_incoming_counter_used(self):
        """Higher incoming counter is accepted."""
        existing = {'kestrel_impact_total_files': 1000}
        incoming = {'kestrel_impact_total_files': 2000}

        result = _apply_monotonic_guard(incoming, existing)
        assert result['kestrel_impact_total_files'] == 2000
