"""Backwards-compatibility tests for database migration.

Loads legacy database CSV fixtures (generated by cloud agent — see
fixtures/legacy_databases/CLOUD_AGENT_INSTRUCTIONS.md) and verifies that
load_database() correctly migrates them to the current schema.

Tests skip cleanly if no fixtures are present yet.
"""

import pytest
import shutil
import pandas as pd
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from kestrel_analyzer.database import (
    load_database,
    load_scenedata,
    _needs_upgrade,
    parse_file_size,
    BASE_COLUMNS,
    LEGACY_USER_COLUMNS,
)


pytestmark = pytest.mark.compat


FIXTURE_DIR = Path(__file__).parent.parent / "fixtures" / "legacy_databases"


def _list_legacy_fixtures():
    """Return list of legacy database CSV fixture paths."""
    if not FIXTURE_DIR.exists():
        return []
    return sorted([f for f in FIXTURE_DIR.glob("v_*_kestrel_database.csv")])


_LEGACY_FIXTURES = _list_legacy_fixtures()

_skip_no_fixtures = pytest.mark.skipif(
    not _LEGACY_FIXTURES,
    reason="No legacy database fixtures present yet — pending cloud agent work."
)


@pytest.fixture
def legacy_csv_in_temp_dir(tmp_path, request):
    """Copy a legacy CSV fixture into a temp .kestrel/ dir for migration testing."""
    fixture_path = request.param
    kestrel_dir = tmp_path / ".kestrel"
    kestrel_dir.mkdir()
    target_csv = kestrel_dir / "kestrel_database.csv"
    shutil.copy(fixture_path, target_csv)
    return tmp_path, fixture_path


# Parametrize across every legacy fixture present
@_skip_no_fixtures
@pytest.mark.parametrize(
    "legacy_csv_in_temp_dir",
    _LEGACY_FIXTURES if _LEGACY_FIXTURES else [None],
    indirect=True,
    ids=[p.name for p in _LEGACY_FIXTURES] if _LEGACY_FIXTURES else ["no-fixtures"]
)
class TestLegacyDatabaseMigration:
    """Tests that run against every legacy fixture."""

    def test_legacy_db_needs_upgrade(self, legacy_csv_in_temp_dir):
        """A legacy DB with old columns should report needs_upgrade=True."""
        tmp_path, fixture_path = legacy_csv_in_temp_dir
        kestrel_dir = tmp_path / ".kestrel"

        # Load the fixture as a DataFrame
        df = pd.read_csv(kestrel_dir / "kestrel_database.csv")

        # If this fixture has any legacy user columns AND no scenedata yet, it should need upgrade
        has_legacy = any(col in df.columns for col in LEGACY_USER_COLUMNS)
        if has_legacy:
            assert _needs_upgrade(df, str(kestrel_dir)) == True

    def test_migration_completes_without_error(self, legacy_csv_in_temp_dir):
        """load_database() must succeed on every legacy fixture."""
        tmp_path, fixture_path = legacy_csv_in_temp_dir
        kestrel_dir = tmp_path / ".kestrel"

        db, db_path = load_database(str(kestrel_dir), "test_analyzer", None)
        assert isinstance(db, pd.DataFrame)
        assert len(db) > 0  # All fixtures have 4 rows

    def test_migration_no_filenames_lost(self, legacy_csv_in_temp_dir):
        """No filenames are lost during migration."""
        tmp_path, fixture_path = legacy_csv_in_temp_dir
        kestrel_dir = tmp_path / ".kestrel"

        original = pd.read_csv(kestrel_dir / "kestrel_database.csv")
        original_filenames = set(original['filename'].dropna())

        db, db_path = load_database(str(kestrel_dir), "test_analyzer", None)
        migrated_filenames = set(db['filename'].dropna())

        # All original filenames must be present
        assert original_filenames == migrated_filenames

    def test_legacy_columns_removed_after_migration(self, legacy_csv_in_temp_dir):
        """After migration, legacy user columns are not in the live DataFrame."""
        tmp_path, fixture_path = legacy_csv_in_temp_dir
        kestrel_dir = tmp_path / ".kestrel"

        original = pd.read_csv(kestrel_dir / "kestrel_database.csv")
        had_legacy = any(col in original.columns for col in LEGACY_USER_COLUMNS)

        if not had_legacy:
            pytest.skip(f"{fixture_path.name} has no legacy columns to migrate")

        db, _ = load_database(str(kestrel_dir), "test_analyzer", None)

        # Legacy columns should not appear in the migrated DataFrame
        for col in LEGACY_USER_COLUMNS:
            assert col not in db.columns, (
                f"Migration failed to drop legacy column '{col}' from {fixture_path.name}"
            )

    def test_file_size_present_but_unknown_after_load(self, legacy_csv_in_temp_dir):
        """Every pre-``file_size`` fixture gains the column as UNKNOWN, not zero.

        ``file_size`` is half of a row's identity. A legacy row has no recorded
        size, and the distinction between "unknown" and "0 bytes" is the whole
        ballgame: if a legacy row loaded as size 0 it would mismatch its own file
        on disk, and the pipeline would re-analyse an entire historical library
        while the repair UI reported every photo as changed.
        """
        tmp_path, fixture_path = legacy_csv_in_temp_dir
        kestrel_dir = tmp_path / ".kestrel"

        original = pd.read_csv(kestrel_dir / "kestrel_database.csv")
        if "file_size" in original.columns:
            pytest.skip(f"{fixture_path.name} already carries file_size")

        db, _ = load_database(str(kestrel_dir), "test_analyzer", None)

        assert "file_size" in db.columns, (
            f"ensure_columns did not backfill file_size for {fixture_path.name}"
        )
        for value in db["file_size"].values:
            assert parse_file_size(value) is None, (
                f"Legacy row in {fixture_path.name} produced a concrete size "
                f"{value!r}; legacy sizes must read as unknown."
            )

    def test_rating_migrated_to_scenedata(self, legacy_csv_in_temp_dir):
        """If fixture had inline `rating` column, values appear in scenedata after migration."""
        tmp_path, fixture_path = legacy_csv_in_temp_dir
        kestrel_dir = tmp_path / ".kestrel"

        original = pd.read_csv(kestrel_dir / "kestrel_database.csv")
        if 'rating' not in original.columns:
            pytest.skip(f"{fixture_path.name} has no rating column")

        # Run migration via load_database
        load_database(str(kestrel_dir), "test_analyzer", None)

        # Check scenedata was created with rating info
        scenedata = load_scenedata(str(kestrel_dir))
        # Scenedata should have image_ratings populated
        image_ratings = scenedata.get('image_ratings', {})
        # At least some ratings should have been transferred
        non_zero_ratings = {fn: r for fn, r in image_ratings.items() if r}
        assert len(non_zero_ratings) > 0, (
            f"Expected rating values to transfer to scenedata from {fixture_path.name}"
        )


class TestCurrentSchemaNoUpgrade:
    """Verify that the CURRENT schema is correctly identified as not needing migration."""

    def test_fresh_current_db_no_upgrade(self, tmp_path):
        """A freshly-created DB with current schema → needs_upgrade returns False."""
        kestrel_dir = tmp_path / ".kestrel"
        kestrel_dir.mkdir()

        df = pd.DataFrame(columns=BASE_COLUMNS)
        df.to_csv(kestrel_dir / "kestrel_database.csv", index=False)

        assert _needs_upgrade(df, str(kestrel_dir)) == False
